services:
  monitarr:
    container_name: monitarr
    image: ghcr.io/nickshanks347/monitarr:latest
    ports:
      - 3000:3000
    environment:
      - SONARR_URL=http://sonarr:8989
      - SONARR_API_KEY=YOUR_SONARR_API_KEY
      - RADARR_URL=http://radarr:7878
      - RADARR_API_KEY=YOUR_RADARR_API_KEY
    restart: unless-stopped